name: '格式检查'

on: [push, pull_request, merge_group, workflow_dispatch, workflow_call]

jobs:
  check:
    runs-on: ubuntu-latest
    name: '检查'
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v2

      - name: Report ReviewDog
        if: failure()
        uses: huacnlee/autocorrect-action@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true
